LOG_HID_PATH = '/home/fhx/artstation/log.json'
POSTS_PATH = '/home/fhx/artstation/posts1.json'
TAGS_PATH = '/home/fhx/artstation/tags.json'
CATEGORIES_PATH = '/home/fhx/artstation/categories.json'
CSV_DIR = '/home/fhx/artstation/test.csv'